create table Cat (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL,
    img_name varchar NOT NULL,
    voices int
);

INSERT INTO Cat (name, img_name, voices) VALUES ('Мурка', '2_Мурка.jpg', 0);
INSERT INTO Cat (name, img_name, voices) VALUES ('Себастьян', '3_Себастьян.jpg', 0);
INSERT INTO Cat (name, img_name, voices) VALUES ('Дурбей', '5_Дурбей.jpg', 0);
INSERT INTO Cat (name, img_name, voices) VALUES ('Барсик', '1_Барсик.jpg', 0);
INSERT INTO Cat (name, img_name, voices) VALUES ('Муся', '4_Муся.jpg', 0);