create table Cat (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL,
    img_path varchar NOT NULL,
    voices int
);

INSERT INTO Cat (id, name, img_path, voices) VALUES (2, 'Мурка', '2_Мурка.jpg', 0);
INSERT INTO Cat (id, name, img_path, voices) VALUES (3, 'Себастьян', '3_Себастьян.jpg', 0);
INSERT INTO Cat (id, name, img_path, voices) VALUES (5, 'Дурбей', '5_Дурбей.jpg', 0);
INSERT INTO Cat (id, name, img_path, voices) VALUES (1, 'Барсик', '1_Барсик.jpg', 0);
INSERT INTO Cat (id, name, img_path, voices) VALUES (4, 'Муся', '4_Муся.jpg', 0);